import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.scss";
import NavBar from "./components/NavBar";
import "locomotive-scroll/src/locomotive-scroll.scss";
import { SmoothScrollProvider } from "./context/ScrollProviderContext";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} dark  overflow-x-hidden`}>
        {" "}
        <SmoothScrollProvider>
          <section className="main-container" data-scroll-container>
            {children}{" "}
          </section>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
